FROM postgres:16-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      clang \
      llvm \
      git \
      postgresql-server-dev-16 \
      postgresql-16-pgtap \
      pgtap && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
