FROM postgres:15-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      clang \
      llvm \
      git \
      postgresql-server-dev-15 \
      postgresql-15-pgtap \
      pgtap && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /work
